import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/src/app/lib/utils";
import "./globals.css";
import { AI } from "./actions";
import { ThemeProvider } from "@/components/theme_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
    {/* <MyRuntimeProvider> */}
      <html lang="en" className="h-full">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <body className={cn(inter.className, "h-full")}>{children}</body>
        </ThemeProvider>
      </html>
    {/* </MyRuntimeProvider> */}
    </AI>
  );
}
